#!/bin/bash

option=$1
#set -x
case $option in
    "t1")
       rows=$2
        for (( i=1 ; i <= rows ; i++)); do
            for (( j=1 ; j <= rows-i ; j++)); do
                echo -n " "
            done    
            for (( k = 1 ; k <= i ; k++)); do
                echo -n "*"
            done   
             echo  
        done
        ;;
    "t2")
        rows=$2
        for ((i = 1; i <= rows ; i++)); do
            for ((j = 1; j <= i ; j++ )); do
                echo -n "*"
            done
                echo
        done
        ;;
     "t3")
          rows=$2 
        for ((i = 1; i <= rows ; i++)); do
            for ((k = 1; k <= (rows-i) ; k++)); do
                echo -n " "
            done    
            for ((j = 1; j <= (2*i -1) ; j++ )); do
                echo -n "*"
            done
                echo 
        done
        ;;
    "t4")
        rows=$2 
        for ((i = 1; i <= rows ; i++)); do
            for ((j = rows; j >= i ; j-- )); do
                echo -n "*"
            done
                echo 
        done
        ;;
    "t5")
        rows=$2
        for ((i = rows; i >= 1; i--)); do
            for ((j = i; j < rows; j++)); do
                echo -n " "
            done
            for ((k = 1; k <= i; k++)); do
                echo -n "*"
        done
            echo 
        done
        ;;
    "t6")
        rows=$2 
        for ((i = rows; i >= 1 ; i--)); do
            for ((k = 1; k <= (rows-i) ; k++)); do
                echo -n " "
            done    
            for ((j = 1; j <= (2*i -1) ; j++ )); do
                echo -n "*"
            done
                echo 
        done
        ;;

     "t7")
        rows=$2 
        for ((i = 1; i <= rows ; i++)); do
            for ((k = 1; k <= (rows-i) ; k++)); do
                echo -n " "
            done    
            for ((j = 1; j <= (2*i -1) ; j++ )); do
                echo -n "*"
            done
                echo 
        done
        for ((i = (rows - 1); i >= 1 ; i--)); do
            for ((k = 1; k <= (rows-i) ; k++)); do
                echo -n " "
            done    
            for ((j = 1; j <= (2*i -1) ; j++ )); do
                echo -n "*"
            done
                echo 
        done
        ;;
esac    


